---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true
  when: ansible_os_family != 'FreeBSD'

- name: Restart shard-listener
  ansible.builtin.service:
    name: "{{ 'shard-listener' if ansible_os_family != 'FreeBSD' else 'shard_listener' }}"
    state: restarted
